Vagrant.configure("2") do |config|
  #config.vm.provision "shell", inline: "uname -a"
  #config.vm.provision "shell", name: "mem", inline: "free -m"
  config.vm.box = "debian/12.1"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
  end

  config.vm.define "web" do |web|
  #  web.vm.box = "almalinux/9.2"
    web.vm.hostname = "web"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "web"
  end

  config.vm.define "cli" do |cli|
  end
end
