# -*- mode: ruby -*-
# vi: set ft=ruby :
nodes = {
  :pcm1 => {
        :ip_addr => '192.168.7.150'
  },
  :pcm2 => {
        :ip_addr => '192.168.7.151'
  },
}

Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/9.2"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
  end
  nodes.each do |boxname, boxconfig|
      # настройки виртуальной машины
      config.vm.define boxname do |box|
          box.vm.hostname = boxname.to_s # pcm1, pcm2
          box.vm.network("private_network", ip: boxconfig[:ip_addr])
      end
  end
end
